-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 21:29:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codPro` INT NOT NULL AUTO_INCREMENT,
  `nomePro` VARCHAR(45) NOT NULL,
  `precoVenda` FLOAT NOT NULL,
  `precoCusto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codPro`),
  UNIQUE INDEX `idProduto_UNIQUE` (`codPro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaCompra` (
  `nroCompra` INT NOT NULL AUTO_INCREMENT,
  `dataCompra` DATE NOT NULL,
  `totalNota` FLOAT NOT NULL,
  PRIMARY KEY (`nroCompra`),
  UNIQUE INDEX `idNotaCompra_UNIQUE` (`nroCompra` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemCompra` (
  `idItemCompra` INT NOT NULL AUTO_INCREMENT,
  `quantidadeCompra` INT NOT NULL,
  `valorCompra` FLOAT NOT NULL,
  `Produto_codPro` INT NOT NULL,
  `NotaCompra_nroCompra` INT NOT NULL,
  PRIMARY KEY (`idItemCompra`),
  UNIQUE INDEX `nroCompra_UNIQUE` (`idItemCompra` ASC) VISIBLE,
  INDEX `fk_ItemCompra_Produto_idx` (`Produto_codPro` ASC) VISIBLE,
  INDEX `fk_ItemCompra_NotaCompra1_idx` (`NotaCompra_nroCompra` ASC) VISIBLE,
  CONSTRAINT `fk_ItemCompra_Produto`
    FOREIGN KEY (`Produto_codPro`)
    REFERENCES `mydb`.`Produto` (`codPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemCompra_NotaCompra1`
    FOREIGN KEY (`NotaCompra_nroCompra`)
    REFERENCES `mydb`.`NotaCompra` (`nroCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profissao` (
  `idProfissao` INT NOT NULL AUTO_INCREMENT,
  `nomeProfissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfissao`),
  UNIQUE INDEX `idProfissao_UNIQUE` (`idProfissao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `Profissao_idProfissao` INT NULL,
  PRIMARY KEY (`codCliente`),
  UNIQUE INDEX `codCliente_UNIQUE` (`codCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Profissao1_idx` (`Profissao_idProfissao` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Profissao1`
    FOREIGN KEY (`Profissao_idProfissao`)
    REFERENCES `mydb`.`Profissao` (`idProfissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaVenda` (
  `nroVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `totalVenda` FLOAT NOT NULL,
  `Cliente_codCliente` INT NOT NULL,
  INDEX `fk_NotaVenda_Cliente1_idx` (`Cliente_codCliente` ASC) VISIBLE,
  PRIMARY KEY (`nroVenda`),
  UNIQUE INDEX `idNotaVenda_UNIQUE` (`nroVenda` ASC) VISIBLE,
  CONSTRAINT `fk_NotaVenda_Cliente1`
    FOREIGN KEY (`Cliente_codCliente`)
    REFERENCES `mydb`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemVenda` (
  `idItemVenda` INT NOT NULL AUTO_INCREMENT,
  `quantidadeVenda` INT NOT NULL,
  `valorVenda` VARCHAR(45) NOT NULL,
  `Produto_codPro` INT NOT NULL,
  `NotaVenda_nroVenda` INT NOT NULL,
  PRIMARY KEY (`idItemVenda`),
  UNIQUE INDEX `nroVenda_UNIQUE` (`idItemVenda` ASC) VISIBLE,
  INDEX `fk_ItemVenda_Produto1_idx` (`Produto_codPro` ASC) VISIBLE,
  INDEX `fk_ItemVenda_NotaVenda1_idx` (`NotaVenda_nroVenda` ASC) VISIBLE,
  CONSTRAINT `fk_ItemVenda_Produto1`
    FOREIGN KEY (`Produto_codPro`)
    REFERENCES `mydb`.`Produto` (`codPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVenda_NotaVenda1`
    FOREIGN KEY (`NotaVenda_nroVenda`)
    REFERENCES `mydb`.`NotaVenda` (`nroVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Profissao`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Profissao` (`idProfissao`, `nomeProfissao`) VALUES (1, 'Medico(a)');
INSERT INTO `mydb`.`Profissao` (`idProfissao`, `nomeProfissao`) VALUES (2 , 'Engenheiro(a)');
INSERT INTO `mydb`.`Profissao` (`idProfissao`, `nomeProfissao`) VALUES (3, 'Professor(a)');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`codCliente`, `nomeCliente`, `Profissao_idProfissao`) VALUES (, DEFAULT, 1);
INSERT INTO `mydb`.`Cliente` (`codCliente`, `nomeCliente`, `Profissao_idProfissao`) VALUES (, DEFAULT, 2);
INSERT INTO `mydb`.`Cliente` (`codCliente`, `nomeCliente`, `Profissao_idProfissao`) VALUES (, DEFAULT, 3);
INSERT INTO `mydb`.`Cliente` (`codCliente`, `nomeCliente`, `Profissao_idProfissao`) VALUES (, DEFAULT, 1);
INSERT INTO `mydb`.`Cliente` (`codCliente`, `nomeCliente`, `Profissao_idProfissao`) VALUES (, DEFAULT, NULL);

COMMIT;

